### ISSUE TITLE
Focal: logviewer does not display logs

### ISSUE THREAD

**Issue by lduboeuf** [ruditimmermans/Logviewer#1]
When opening Logviewer on Focal, we have 3 entries ( assets/qml/share), but no logs

**Comment by ruditimmermans** [comment]
Oh that's wierd i update from xenial to focal and i got upstart and logs there.....

**Comment by ruditimmermans** [comment]
I just have reset my device and done a complete new install from focal (no update) and indeed it seems there is no upstart directory with logs anymore.... so i dont know how to slove this and where the logs now are on focal....

**Comment by lduboeuf** [comment]
yes, they are now handled by journalctl. So i have no idea too how it can be done

**Comment by ruditimmermans** [comment]
Me also not wierd when you update from xenial to focal you have logs when do a clean install of focal you have not seems buggy somehwere.....

**Comment by lduboeuf** [comment]
clickable uses this for app logs on Focal:

journalctl --user --no-tail --follow -u lomiri-app-launch--application-click--{package_name}-- 1>&2

**Comment by ruditimmermans** [comment]
Ok that give me a clue i will try some things thanks!

**Comment by lduboeuf** [comment]
that one for not real time view:

journalctl --user --no-pager -u lomiri-app-launch--application-click--{package_name}--

**Comment by ruditimmermans** [comment]
I have been look into it, but i have no clue how to do this so i hope someone would make a PR to fix this, for now i have put the app offline into the store till this is fixed. thanks for the report.

**Comment by ruditimmermans** [comment]
Fixed thanks to Maciek Sopyło
