### ISSUE TITLE
[focal only] teleports push helper entries fill up the log

### ISSUE THREAD

**Issue by Danfro** [ruditimmermans/Logviewer#4]
According to some discussion in developer group, the teleports push helper gets launched every time a notification comes in. Every launch results in an entry in logviewer. Therefore it does create lots and lots of log entries and logviewer is getting cumbersome to search for an app log.

But this seems to be something that needs to be fixed in logviewer.

![grafik](https://user-images.githubusercontent.com/37637312/215290218-ad6c9195-274f-42bb-b742-7bdf0e858b82.png)

**Comment by maciek134** [comment]
Fixed by #7
